{% set name = "bps-stack_coreg_processor" %}
{% set version = "4.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file://{{ RECIPE_DIR }}/../dist/bps_stack_coreg_processor-{{ version }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - numpy
    - xmltodict
    - arepytools ==1.9.0.dev0
    - arepyextras-runner
    - bps-common =={{ version }}
    - perseo-core >=1.0.0

test:
  imports:
    - bps
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Biomass Stack Coregistration Processor package.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aresys srl
