{% set name = "bps-stack_processor" %}
{% set version = "4.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file://{{ RECIPE_DIR }}/../dist/bps_stack_processor-{{ version }}.tar.gz

build:
  noarch: python
  entry_points:
    - bps_stack_processor = bps.stack_processor.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - numpy
    - arepytools ==1.9.0.dev0
    - click
    - xsdata
    - arepyextras-runner
    - bps-common =={{ version }}
    - bps-stack_binaries =={{ version }}
    - bps-stack_pre_processor =={{ version }}
    - bps-stack_coreg_processor =={{ version }}
    - bps-stack_cal_processor =={{ version }}
    - bps-transcoder =={{ version }}
    - perseo-core >=1.0.0
    - gdal >=3.10,<3.11

test:
  imports:
    - bps
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Biomass Stack Processor.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aresys srl
