{% set name = "bps-common" %}
{% set version = "4.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file://{{ RECIPE_DIR }}/../dist/bps_common-{{ version }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - arepyextras-runner
    - numpy
    - arepytools ==1.9.0.dev0
    - xsdata
    - xmlschema
    - gdal >=3.10,<3.11
    - perseo-core >=1.0.0

test:
  imports:
    - bps
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Biomass common package.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aresys srl
