{% set name = "bps-l1_processor" %}
{% set version = "4.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file://{{ RECIPE_DIR }}/../dist/bps_l1_processor-{{ version }}.tar.gz

build:
  noarch: python
  entry_points:
    - bps_l1_processor = bps.l1_processor.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - numpy
    - arepytools ==1.9.0.dev0
    - click
    - xsdata
    - arepyextras-runner
    - matplotlib-base
    - unlzw3
    - shapely
    - pyproj
    - netcdf4
    - bps-common =={{ version }}
    - bps-l1_binaries =={{ version }}
    - bps-l1_pre_processor =={{ version }}
    - bps-l1_core_processor =={{ version }}
    - bps-transcoder =={{ version }}
    - perseo-core >=1.0.0

test:
  imports:
    - bps
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Biomass L1 Processor.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aresys srl
